/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GridPage: typeof import('./components/Grid-Page.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechRecognition: typeof import('./components/Speech-Recognition.vue')['default']
    Syllable: typeof import('./components/Syllable.vue')['default']
    ThePwaReloadDialog: typeof import('./components/ThePwaReloadDialog.vue')['default']
    Transcribe: typeof import('./components/Transcribe.vue')['default']
  }
}
